"""mode value labels."""
from .labeled_enum import LabeledEnum


class Mode(LabeledEnum):
    """mode value labels."""

    WALK_OR_JOG_OR_WHEELCHAIR = (1, "Walk/jog/wheelchair")
    STANDARD_BICYCLE_MY_HOUSEHOLDS = (2, "Standard bicycle (household)")
    BORROWED_BICYCLE = (3, "Borrowed bicycle")
    OTHER_RENTED_BICYCLE = (4, "Other rented bicycle")
    OTHER = (5, "Other")
    HOUSEHOLD_VEHICLE_1 = (6, "Household vehicle 1")
    HOUSEHOLD_VEHICLE_2 = (7, "Household vehicle 2")
    HOUSEHOLD_VEHICLE_3 = (8, "Household vehicle 3")
    HOUSEHOLD_VEHICLE_4 = (9, "Household vehicle 4")
    HOUSEHOLD_VEHICLE_5 = (10, "Household vehicle 5")
    HOUSEHOLD_VEHICLE_6 = (11, "Household vehicle 6")
    HOUSEHOLD_VEHICLE_7 = (12, "Household vehicle 7")
    HOUSEHOLD_VEHICLE_8 = (13, "Household vehicle 8")
    HOUSEHOLD_VEHICLE_9 = (14, "Household vehicle 9")
    HOUSEHOLD_VEHICLE_10 = (15, "Household vehicle 10")
    OTHER_VEHICLE_IN_HOUSEHOLD = (16, "Other vehicle (household)")
    RENTAL_CAR = (17, "Rental car")
    CARSHARE_SERVICE = (18, "Carshare (Zipcar, etc.)")
    VANPOOL = (21, "Vanpool")
    OTHER_VEHICLE_NOT_MY_HOUSEHOLDS = (22, "Other vehicle (non-household)")
    LOCAL_PUBLIC_BUS = (23, "Local public bus")
    SCHOOL_BUS = (24, "School bus")
    INTERCITY_BUS = (25, "Intercity bus (Greyhound, etc.)")
    OTHER_PRIVATE_SHUTTLE_OR_BUS = (26, "Private shuttle/bus")
    PARATRANSIT_OR_DIAL_A_RIDE = (27, "Paratransit/Dial-A-Ride")
    OTHER_BUS = (28, "Other bus")
    BART = (30, "BART")
    AIRPLANE_OR_HELICOPTER = (31, "Airplane/helicopter")
    CAR_FROM_WORK = (33, "Work car")
    FRIEND_OR_RELATIVE_OR_COLLEAGUES_CAR = (34, "Friend/relative/colleague car")
    REGULAR_TAXI = (36, "Regular taxi")
    UNIVERSITY_OR_COLLEGE_SHUTTLE_OR_BUS = (38, "University/college shuttle")
    INTERCITY_OR_COMMUTER_RAIL = (41, "Intercity/commuter rail (ACE, Amtrak, Caltrain)")
    OTHER_RAIL = (42, "Other rail")
    SKATEBOARD_OR_ROLLERBLADE = (43, "Skateboard/rollerblade")
    GOLF_CART = (44, "Golf cart")
    ATV = (45, "ATV")
    OTHER_MOTORCYCLE_IN_HOUSEHOLD = (47, "Motorcycle (household)")
    UBER_LYFT_OR_OTHER_SMARTPHONE_APP_RIDE_SERVICE = (49, "Rideshare (Uber, Lyft, etc.)")
    MUNI_METRO = (53, "MUNI Metro")
    OTHER_MOTORCYCLE_NOT_MY_HOUSEHOLDS = (54, "Motorcycle (non-household)")
    EXPRESS_BUS_OR_TRANSBAY_BUS = (55, "Express/Transbay bus")
    PEER_TO_PEER_CAR_RENTAL = (59, "Peer-to-peer rental (Turo, etc.)")
    OTHER_HIRED_CAR_SERVICE = (60, "Hired car (black car, limo)")
    RAPID_TRANSIT_BUS_BRT = (61, "Rapid transit bus (BRT)")
    EMPLOYER_PROVIDED_SHUTTLE_OR_BUS = (62, "Employer shuttle/bus")
    MEDICAL_TRANSPORTATION_SERVICE = (63, "Medical transportation")
    LOCAL_PRIVATE_BUS = (67, "Local private bus")
    CABLE_CAR_OR_STREETCAR = (68, "Cable car/streetcar")
    BIKE_SHARE_STANDARD_BICYCLE = (69, "Bike-share (standard)")
    BIKE_SHARE_ELECTRIC_BICYCLE = (70, "Bike-share (electric)")
    MOPED_SHARE = (73, "Moped-share (Scoot, etc.)")
    SEGWAY = (74, "Segway")
    OTHER_75 = (75, "Other")
    CARPOOL_MATCH = (76, "Carpool match (Waze, etc.)")
    PERSONAL_SCOOTER_OR_MOPED_NOT_SHARED = (77, "Personal scooter/moped")
    PUBLIC_FERRY_OR_WATER_TAXI = (78, "Ferry/water taxi")
    OTHER_BOAT = (80, "Other boat (kayak, etc.)")
    ELECTRIC_BICYCLE_MY_HOUSEHOLDS = (82, "Electric bicycle (household)")
    SCOOTER_SHARE = (83, "Scooter-share (Bird, Lime, etc.)")
    HOUSEHOLD_VEHICLE_OR_MOTORCYCLE = (100, "Household vehicle/motorcycle")
    OTHER_VEHICLE = (101, "Other vehicle (rental, carshare, etc.)")
    BUS_SHUTTLE_OR_VANPOOL = (102, "Bus/shuttle/vanpool")
    BICYCLE = (103, "Bicycle")
    OTHER_104 = (104, "Other")
    RAIL = (105, "Rail (train, BART, MUNI, etc.)")
    UBER_OR_LYFT_TAXI_OR_CAR_SERVICE = (106, "Uber/Lyft/taxi/car service")
    MICROMOBILITY = (107, "Micromobility (scooter, moped, etc.)")
    MISSING = (995, "Missing Response")


class ModeType(LabeledEnum):
    """mode_type value labels."""

    canonical_field_name = "mode_type"

    WALK = (1, "Walk")
    BIKE = (2, "Bike")
    BIKESHARE = (3, "Bikeshare")
    SCOOTERSHARE = (4, "Scootershare")
    TAXI = (5, "Taxi")
    TNC = (6, "TNC")
    OTHER = (7, "Other")
    CAR = (8, "Car")
    CARSHARE = (9, "Carshare")
    SCHOOL_BUS = (10, "School bus")
    SHUTTLE_OR_VANPOOL = (11, "Shuttle/vanpool")
    FERRY = (12, "Ferry")
    TRANSIT = (13, "Transit")
    LONG_DISTANCE_PASSENGER = (14, "Long distance passenger")
    MISSING = (995, "Missing Response")

class ModeTypeMap:
    """Mapping from detailed mode codes to mode types."""
    # Need to populate this...
